
server:
  port: 8090
  servlet:
    context-path: /api
spring:
  #main:
    #web-application-type: none
  data:
    mongodb:
      #uri: mongodb://mongodb-server1:27017/genx-base-test
      uri: mongodb://192.168.2.10:27017/genx-processor-test

generator:
  modelPackage: model
  controllerPackage: controller
  servicePackage: service
  utilPackage: util
  constantPackage: constant
  repositoryPackage: repository
  processors:
  - id: model
    template: javamodelclass.html
    packageName: model.dao
    suffix: ""
  - id: dto
    template: javadtoclass.html
    packageName: model.dto
    suffix: "DTO"
  - id: controller
    template: javacontrollerclass.html
    packageName: controller
    suffix: Controller
  - id: service
    template: javaserviceclass.html
    packageName: service
    suffix: Service
  - id: util
    template: javautilclass.html
    packageName: util
    suffix: Util
  - id: constant
    template: javaconstantclass.html
    packageName: constant
    suffix: Constant
  - id: repository
    template: javarepositoryclass.html
    packageName: repository
    suffix: Repository
    
  #- id: ui
  #  template: ui/reactmodel.html
  #  packageName: ui
  #  suffix: UI
  output-dir: generated
  domain-models:
    - id: tenant
      name: Tenant
      packageName: tenant
      className: Tenant
      fields:
         - id: title
           javaType: String
           title: Title
         - id: className
           javaType: String
           title: ClassName
         - id: description
           javaType: String
           title: Description
         - id: name
           javaType: String
           title: name
         - id: packageName
           javaType: String
           title: packageName
         - id: uiSrcPath
           javaType: String
           title: uiSrcPath
         - id: javaSrcPath
           javaType: String
           title: javaSrcPath
    - id: entity
      name: Entity
      packageName: entity
      className: Entity
      fields:
         - id: title
           javaType: String
           title: Title
         - id: className
           javaType: String
           title: ClassName
         - id: description
           javaType: String
           title: Description
         - id: name
           javaType: String
           title: name
         - id: packageName
           javaType: String
           title: packageName
         - id: tenant
           javaType: String
           title: Tenant
           reference: true
           referenceModelId: tenant
           referenceTitleFromRecord: 'record.title'
           referenceTitles:
             - title
    - id: field
      name: Field
      packageName: field
      className: Field
      fields:
         - id: name
           javaType: String
           title: Name
         - id: type
           javaType: String
           title: Type
         - id: supType
           javaType: String
           title: SuperType
         - id: title
           javaType: String
           title: Title
         - id: description
           javaType: String
           title: Description
         - id: longText
           javaType: Boolean
           title: Is text Long?
         - id: file
           javaType: Boolean
           title: Is File?
         - id: playableVideo
           javaType: Boolean
           title: Is playable video?
         - id: reference
           javaType: Boolean
           title: Is reference?
         - id: referenceMultiple
           javaType: Boolean
           title: Is reference multiple?
         - id: referenceTabbed
           javaType: Boolean
           title: Is reference tabbed?
         - id: referenceAsForm
           javaType: Boolean
           title: Is reference as form?
         - id: referenceEntityName
           javaType: String
           title: Reference Entity Name
         - id: referenceTitleFromRecord
           javaType: String
           title: Reference Title From Record record =>
         - id: referenceTitles
           javaSupType: List
           javaType: String
           title: Reference Titles for List
         - id: entity
           javaType: String
           title: Entity
           reference: true
           referenceModelId: entity
           #referenceTitleFromRecord: '(await AxiosInstance.get("/api/tenant/" + record.tenant)).data.title + " " +record.title'
           referenceTitleFromRecord: 'record.title'
           referenceTitles:
             - title

logging:
  level:
    com.genx: debug
    